### ISSUE TITLE
Investigate the missing videos in blog page 

### ISSUE THREAD

**Issue by naseerkassar** [Foursevens/f7-wordpress-theme#99] opened 2019-10-15 11:05 UTC
### steps

1. Go to https://f7-theme.moeriki.now.sh/en/blog

2. Filter for videos  

### Expected 
We expect to see any video content 

### Result
We are getting empty page

**Comment by Moeriki** [comment] 2019-11-06 16:29
I can't reproduce an issue. Is this still the case? If so could provide a reproducible example.

**Comment by naseerkassar** [comment] 2019-11-12 10:18
I updated the description of the bug and now it is more clear thank you for the help on how to write effective bug description

**Comment by Moeriki** [comment] 2020-02-05 13:02
Still can't produce. Closing for now.

**Closed by Moeriki** 2020-02-05 13:02 UTC
Labels: analysis
